name: Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker Image Tag (yyyyMMdd)'
        required: true

env:
  DEBIAN_FRONTEND: noninteractive
  DOCKER_IMAGE_NAME1: "ubuntu24-dotnet8-opencv4.12.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: validate input
        run: |
          if [[ ! ${{ github.event.inputs.docker_image_tag }} =~ ^[0-9]{8}$ ]]; then
            echo "::error Invalid tag name '${{ github.event.inputs.docker_image_tag }}'"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: docker build
        run: |
          cd docker/${DOCKER_IMAGE_NAME1}
          docker build -t ghcr.io/shimat/opencvsharp/${DOCKER_IMAGE_NAME1}:${{ github.event.inputs.docker_image_tag }} .

      - name: docker login
        run: |
          echo ${{secrets.GH_PACKAGES_PAT}} | docker login ghcr.io -u shimat --password-stdin

      - name: docker push
        run: |
          docker push ghcr.io/shimat/opencvsharp/${DOCKER_IMAGE_NAME1}:${{ github.event.inputs.docker_image_tag }}
